version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/japper

    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
          - sbt-deps-{{ checksum "project/Dependencies.scala" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "project/build.properties" }}
          - sbt-deps-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.cache/coursier
            - ~/.ivy2/cache
            - ~/.sbt/boot
          key: sbt-deps-{{ checksum "project/Dependencies.scala" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "project/build.properties" }}

      - run: cat /dev/null | sbt test:test

  publish:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/japper

    environment:
      TERM: dumb

    steps:
      - checkout
      - attach_workspace:
          at: ~/japper
      - restore_cache:
          keys:
            - sbt-deps-{{ checksum "project/Dependencies.scala" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "project/build.properties" }}
            - sbt-deps-
      - run:
          name: Publish
          command: |
            mkdir -p ~/.sbt/gpg
            echo $SECRING_ASC | base64 --decode > ~/.sbt/gpg/secring.asc
            cat /dev/null | sbt publishSigned

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
